### ISSUE TITLE
 unresolved external symbol jinit_arith_encoder referenced in function hoops_jinit_compress_master

### ISSUE THREAD

**Issue by aditya1331** [intelxai/EXT_libjpeg-9e#1]
Hello I'm Aditya
I facing issue in finding the definition of the above function. Hence it would be really helpful if the file and line of the function definition is answered so that I could verify if the file is present and included.

Thanks

**Comment by intelxai** [comment]
Hello Aditya,

I believe that error only happens if 1) you are trying to install on a unsupported platform or 2) you haven’t followed the installation instructions as described in the READ.ME from intelxAI/ EXT_libjpeg-9e<https://github.com/intelxai/EXT_libjpeg-9e>

Note also that the README is an addendum, or supplemental information for the libjpeg9e readme<https://github.com/intelxai/jpeg-9e/blob/main/README> of the libjpeg-9e package.

The issue is most probably one of not having followed the build/make instructions.

Best of luck.

André


De : Aditya Deshpande ***@***.***>
Date : lundi, 18 décembre 2023 à 02:09
À : intelxai/EXT_libjpeg-9e ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [intelxai/EXT_libjpeg-9e] unresolved external symbol jinit_arith_encoder referenced in function hoops_jinit_compress_master (Issue #1)

Hello I'm Aditya
I facing issue in finding the definition of the above function. Hence it would be really helpful if the file and line of the function definition is answered so that I could verify if the file is present and included.

Thanks
